var Mathematics = parseFloat(prompt("Please enter Mathematics number"));
var Biology = parseFloat(prompt("Please enter Biology number"));
var Chemistry = parseFloat(prompt("Please enter Chemistry number"));
var Physics = parseFloat(prompt("Please enter Physics number"));
var Bangla = parseFloat(prompt("Please enter Bangla number"));
var average = Mathematics + Biology + Chemistry + Physics + Bangla; 
average /= 5;
// var price = parseInt(prompt("cost of 1 kg of oranges and 1 kg of apples"));
document.getElementById("demo").innerHTML = average.toFixed(2);
